const os=require('os');
console.log(os.freemem());
console.log(os.hostname());
console.log(os.platform());
console.log(os.release());
console.log(os.type());
console.log(os.uptime());
console.log(os.userInfo());
console.log(os.totalmem());
console.log(os.cpus());
console.log(os.networkInterfaces());
console.log(os.EOL);